apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-frontend
  template:
    metadata:
      labels:
        app: attendance-frontend
    spec:
      containers:
      - name: frontend
        image: attendance-frontend:1.0
        ports:
        - containerPort: 80