apiVersion: v1
kind: Service
metadata:
  name: attendance-frontend-service
spec:
  type: NodePort
  selector:
    app: attendance-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080